print("Oi")
print(10+20*30)
print(4**2/30)
a=4 
c=5.0
print(a==c)
b=10
a=4
print(a<b)
d=1
print(d>b)
f=5
print(c!=f)
print(a==b)
print(c<d)
print(b>a)
print(c>=f)
print(f>=c)
print(c<=c)
print(c<=f)
print(len("Melissa"))
print("sim".upper())
s="melissa"
print(s.startswith("me"))
print("WAVE".lower())
print("mel"in"melissa")
print("melissa".replace("me","c"))